### ISSUE TITLE
Line number shenanigans

### ISSUE THREAD

**Issue by ghost** [JacksonKearl/vscode-search-editor-apply-changes#9]
The line numbers on the left hand side dictate where your edits end up, which is something I found out while copy-pasting some lines and not noticing the line numbers got copied over as well.

A solution — without knowing anything about VSCode plugin development — would be having the plugin change search results so that there are markers not only for every _file_ containing matches, but for _the lines containing them_ as well.

It would certainly be safer than trying to do some sort of "smart" scanning for mistakes after the fact.
It would also allow for a feature where you can _add and remove_ lines from inside the search editor.

![vscode-search-editor-apply-changes](https://user-images.githubusercontent.com/99724089/159884568-e8858f45-64ba-4108-899c-f474f415c210.gif)

**Comment by JacksonKearl** [comment]
Unfortunately that's not something the extension has control over.
